### ISSUE TITLE
Something wrong happen "not found in PATH: xenmigrate"

### ISSUE THREAD

**Issue by RunningXJ** [trimstray/pvimport#3]
hi!
thank you for your script first!
I meet a problem when used to work!
it display " not found in PATH: xenmigrate"
I have execute setup.sh and look forward to your reply

**Comment by trimstray** [comment]
Hi @RunningXJ!

This output tell You about missing `xenmigrate` tool in `PATH` variable.

Fix:

```
wget https://raw.githubusercontent.com/akh13/xenmigrate.py/master/xenmigrate.py -O /usr/local/bin/xenmigrate

chmod +x /usr/local/bin/xenmigrate
```

**Comment by RunningXJ** [comment]
thanks!
